<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Costo_descripcion extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Costo_descripcion_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    } 
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of costo_descripcion
     */
    function index()
    {
        if($this->acceso(118)){
            $data['page_title'] = "Costo Descripcion";
            
            $data['costo_descripcion'] = $this->Costo_descripcion_model->get_all_costo_descripcion();

            $data['_view'] = 'costo_descripcion/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new costo_descripcion
     */
    function add()
    {
        if($this->acceso(118)){
            $data['page_title'] = "Costo Descripción";
            $this->load->library('form_validation');
            $this->form_validation->set_rules('costodesc_descripcion','Costo Descripción','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {
                $params = array(
                    'costodesc_descripcion' => $this->input->post('costodesc_descripcion'),
                );

                $costodesc_id = $this->Costo_descripcion_model->add_costo_descripcion($params);
                redirect('costo_descripcion/index');
            }
            else
            {            
                $data['_view'] = 'costo_descripcion/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a costo_descripcion
     */
    function edit($costodesc_id)
    {
        if($this->acceso(118)){
            $data['page_title'] = "Costo Descripción";
            // check if the costo_descripcion exists before trying to edit it
            $data['costo_descripcion'] = $this->Costo_descripcion_model->get_costo_descripcion($costodesc_id);
            if(isset($data['costo_descripcion']['costodesc_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('costodesc_descripcion','Costo Descripción','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                if($this->form_validation->run())     
                {
                    $params = array(
                        'costodesc_descripcion' => $this->input->post('costodesc_descripcion'),
                    );
                    $this->Costo_descripcion_model->update_costo_descripcion($costodesc_id,$params);            
                    redirect('costo_descripcion/index');
                }
                else
                {
                    $data['_view'] = 'costo_descripcion/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The costo_descripcion you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting costo_descripcion
     */
    function remove($costodesc_id)
    {
        if($this->acceso(118)){
        $costo_descripcion = $this->Costo_descripcion_model->get_costo_descripcion($costodesc_id);
        // check if the costo_descripcion exists before trying to delete it
        if(isset($costo_descripcion['costodesc_id']))
        {
            $this->Costo_descripcion_model->delete_costo_descripcion($costodesc_id);
            redirect('costo_descripcion/index');
        }
        else
            show_error('The costo_descripcion you are trying to delete does not exist.');
        }
    }
    
    /* * añadir descripcion en costo operativo */
    function aniadirdescripcion()
    {
        if($this->acceso(118)) {
            if ($this->input->is_ajax_request()) {
                //$this->load->model('Categoria_producto_model');
                $parametro = $this->input->post('parametro');
                if($parametro != ""){
                    $params = array(
                    'costodesc_descripcion' => $parametro,
                    );
                    $costodesc_id = $this->Costo_descripcion_model->add_costo_descripcion($params);
                    $datos = $this->Costo_descripcion_model->get_costo_descripcion($costodesc_id);
                    echo json_encode($datos);
                }else{
                    echo json_encode(null);
                }
            }
            else
            {                 
                show_404();
            }
        }
    }

    function get_costo_descripcion(){
        if($this->input->is_ajax_request()){
            $result = $this->Costo_descripcion_model->get_all_costo_descripcion();
            echo json_encode($result);
        }
    }
}
