<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_produccion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detalle_produccion_model');
        $this->load->model('Estado_model');
        $this->load->model('Producto_model');
        $this->load->model('Inventario_model');
        $this->load->model('Produccion_model');
    } 
    
    function get_all_detalle(){
        if ($this->input->is_ajax_request()) {
            $area_id = $this->input->post("area_id");
            $result = $this->Detalle_produccion_model->get_all_produccion($area_id);
            echo json_encode($result);
        }else{
            show_404();
        }
    }

    function pasar_siguiente_estado(){
        if ($this->input->is_ajax_request()){
            $detproduccion_id = $this->input->post("detproduccion_id");
            $estado_id = $this->input->post("estado_id");
            if ($estado_id < 35 ) {
                $estado_id++;
            }else{
                $estado_id = 33;
            }
            $params = array(
                'estado_id'=>$estado_id,
            );
            $this->Detalle_produccion_model->update_detalle($detproduccion_id,$params);
        }else{
            show_404();
        }
    }
    function update_detproduccion(){
        if($this->input->is_ajax_request()){
            $detproduccion_id = $this->input->post("detproduccion_id");
            $perdida = $this->input->post("perdida");
            $observacion = $this->input->post("observacion");
            $detproduccion = $this->Detalle_produccion_model->get_detproduccion($detproduccion_id);
            $params = array(
                'detproduccion_perdida' => $detproduccion[0]['detproduccion_perdida'] + $perdida,
                'detproduccion_observacion' => $observacion,
            );
            $this->Detalle_produccion_model->update_detalle($detproduccion_id, $params);
        }else{
            show_404();
        }
    }

    function incrementar_inventario(){
        if ($this->input->is_ajax_request()) {
            $cantidad = $this->input->post('cantidad');
            $producto = $this->input->post('producto_id');
            $detproduccion_id = $this->input->post("detproduccion_id");
            $params = array(
                "estado_id"=>38
            );
            $this->Detalle_produccion_model->update_detalle($detproduccion_id,$params);
            $this->Inventario_model->incrementar_inventario($cantidad,$producto);
        }else{
            show_404();
        }
    }
}
