<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perdida_detalle extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perdida_detalle_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    } 
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of perdida_detalle
     */
    function index()
    {
        //if($this->acceso(118)){
            $data['page_title'] = "Perdida detalle";
            
            $data['perdida_detalle'] = $this->Perdida_detalle_model->get_all_perdida_detalle();

            $data['_view'] = 'perdida_detalle/index';
            $this->load->view('layouts/main',$data);
        //}
    }

    /*
     * Adding a new perdida_detalle
     */
    function add()
    {
        //if($this->acceso(118)){
            $data['page_title'] = "Perdida detalle";
            $this->load->library('form_validation');
            $this->form_validation->set_rules('perdidad_descripcion','Perdida detalle','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {
                $params = array(
                    'perdidaf_id' => $this->input->post('perdidaf_id'),
                    'perdidad_descripcion' => $this->input->post('perdidad_descripcion'),
                );

                $perdidad_id = $this->Perdida_detalle_model->add_perdida_detalle($params);
                redirect('perdida_detalle/index');
            }
            else
            {
                $this->load->model('Perdida_factor_model');
                $data['all_perdida_factor'] = $this->Perdida_factor_model->get_all_perdida_factor();
                
                $data['_view'] = 'perdida_detalle/add';
                $this->load->view('layouts/main',$data);
            }
        //}
    }  

    /*
     * Editing a perdida_detalle
     */
    function edit($perdidad_id)
    {
        //if($this->acceso(118)){
            $data['page_title'] = "Perdida detalle";
            // check if the perdida_detalle exists before trying to edit it
            $data['perdida_detalle'] = $this->Perdida_detalle_model->get_perdida_detalle($perdidad_id);
            if(isset($data['perdida_detalle']['perdidaf_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('perdidad_descripcion','Perdida detalle','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                if($this->form_validation->run())     
                {
                    $params = array(
                        'perdidaf_id' => $this->input->post('perdidaf_id'),
                        'perdidad_descripcion' => $this->input->post('perdidad_descripcion'),
                    );
                    $this->Perdida_detalle_model->update_perdida_detalle($perdidad_id,$params);            
                    redirect('perdida_detalle/index');
                }
                else
                {
                    $this->load->model('Perdida_factor_model');
                    $data['all_perdida_factor'] = $this->Perdida_factor_model->get_all_perdida_factor();
                    
                    $data['_view'] = 'perdida_detalle/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The perdida_detalle you are trying to edit does not exist.');
        //}
    } 

    /*
     * Deleting perdida_detalle
     */
    function remove($perdidad_id)
    {
        //if($this->acceso(118)){
        $perdida_detalle = $this->Perdida_detalle_model->get_perdida_detalle($perdidad_id);
        // check if the perdida_detalle exists before trying to delete it
        if(isset($perdida_detalle['perdidad_id']))
        {
            $this->Perdida_detalle_model->delete_perdida_detalle($perdidad_id);
            redirect('perdida_detalle/index');
        }
        else
            show_error('The perdida_detalle you are trying to delete does not exist.');
        //}
    }
}
