<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perdida_factor extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perdida_factor_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    } 
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of perdida_factor
     */
    function index()
    {
        //if($this->acceso(118)){
            $data['page_title'] = "Perdida factor";
            
            $data['perdida_factor'] = $this->Perdida_factor_model->get_all_perdida_factor();

            $data['_view'] = 'perdida_factor/index';
            $this->load->view('layouts/main',$data);
        //}
    }

    /*
     * Adding a new perdida_factor
     */
    function add()
    {
        //if($this->acceso(118)){
            $data['page_title'] = "Perdida factor";
            $this->load->library('form_validation');
            $this->form_validation->set_rules('perdidaf_descripcion','Perdida factor','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {
                $params = array(
                    'perdidaf_descripcion' => $this->input->post('perdidaf_descripcion'),
                );

                $perdidaf_id = $this->Perdida_factor_model->add_perdida_factor($params);
                redirect('perdida_factor/index');
            }
            else
            {            
                $data['_view'] = 'perdida_factor/add';
                $this->load->view('layouts/main',$data);
            }
        //}
    }  

    /*
     * Editing a perdida_factor
     */
    function edit($perdidaf_id)
    {
        //if($this->acceso(118)){
            $data['page_title'] = "Perdida factor";
            // check if the perdida_factor exists before trying to edit it
            $data['perdida_factor'] = $this->Perdida_factor_model->get_perdida_factor($perdidaf_id);
            if(isset($data['perdida_factor']['perdidaf_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('perdidaf_descripcion','Perdida factor','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                if($this->form_validation->run())     
                {
                    $params = array(
                        'perdidaf_descripcion' => $this->input->post('perdidaf_descripcion'),
                    );
                    $this->Perdida_factor_model->update_perdida_factor($perdidaf_id,$params);            
                    redirect('perdida_factor/index');
                }
                else
                {
                    $data['_view'] = 'perdida_factor/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The perdida_factor you are trying to edit does not exist.');
        //}
    } 

    /*
     * Deleting perdida_factor
     */
    function remove($perdidaf_id)
    {
        //if($this->acceso(118)){
        $perdida_factor = $this->Perdida_factor_model->get_perdida_factor($perdidaf_id);
        // check if the perdida_factor exists before trying to delete it
        if(isset($perdida_factor['perdidaf_id']))
        {
            $this->Perdida_factor_model->delete_perdida_factor($perdidaf_id);
            redirect('perdida_factor/index');
        }
        else
            show_error('The perdida_factor you are trying to delete does not exist.');
        //}
    }
}
