<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    // /*
    //  * Get unidad by unidad_id
    //  */
    function get_area($area_id)
    {
        return $this->db->get_where('area',array('area_id'=>$area_id))->row_array();
    }
        
    /*
     * Get all unidad
     */
    function get_all_area(){
        $area = $this->db->query(
            "SELECT
                u.*, e.estado_descripcion
            FROM
                area as u,
                estado as e
            WHERE
                u.estado_id = e.estado_id
                ORDER BY area_id ASC
        ")->result_array();

        return $area;
    }

    /*
     * function to add new unidad
     */
    function add_area($params)
    {
        $this->db->insert('area',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update area
     */
    function update_area($area_id,$params)
    {
        $this->db->where('area_id',$area_id);
        return $this->db->update('area',$params);
    }
    /**
     * get ubicaiones disponibles
     */
    function get_disponibles($controli_id){
        return $this->db->query(
            "SELECT u.*
            from area u 
            left join (select cu.*
                        from control_area cu
                        where cu.controli_id = $controli_id) as cu2 on u.area_id = cu2.area_id
            where cu2.controlu_id is null"
        )->result_array();
    }
}
