<?php
/* 
* Generated by CRUDigniter v3.2 
* www.crudigniter.com
*/

class Costo_model extends CI_Model{
    function __construct()
    {
        parent::__construct();
    }
    /**
     * Return all costos for a producto
     */
    function get_all_costos(){
        return $this->db->query(
            "SELECT c.*, e.estado_descripcion 
            FROM costo c
            left join estado e on e.estado_id = c.estado_id
            where 1 = 1"
        )->result_array();
    }

    function add_costo($params){
        $this->db->insert('costo',$params);
        return $this->db->insert_id();
    }

    function update_costo($costo_id,$params){
        $this->db->where('costo_id',$costo_id);
        return $this->db->update('costo',$params);
    }

    function get_costo($costo_id){
        return $this->db->query(
            "SELECT c.*
            from costo c
            where c.costo_id = $costo_id"
        )->row_array();
    }

    function delete_costo_producto($costo_producto){
        return $this->db->delete('costo_producto',array('cproducto_id'=>$costo_producto));
    }
}
