<?php
/* 
* Generated by CRUDigniter v3.2 
* www.crudigniter.com
*/

class Costo_model extends CI_Model{
    function __construct()
    {
        parent::__construct();
    }
    /**
     * Return all costos for a producto
     */
    function get_all_costos(){
        return $this->db->query(
            "SELECT c.*, e.estado_descripcion 
            FROM costo c
            left join estado e on e.estado_id = c.estado_id
            where 1 = 1"
        )->result_array();
    }

    function add_costo($params){
        $this->db->insert('costo',$params);
        return $this->db->insert_id();
    }

    function update_costo($costo_id,$params){
        $this->db->where('costo_id',$costo_id);
        return $this->db->update('costo',$params);
    }

    function get_costo($costo_id){
        return $this->db->query(
            "SELECT c.*
            from costo c
            where c.costo_id = $costo_id"
        )->row_array();
    }
    /**
     * retorna costos de una categoria
     */
    function get_costo_categoria($categoria_id = 1){
        return $this->db->query(
            "SELECT c.*
            from costo c 
            left join categoria_costo cc on cc.catcosto_id = c.catcosto_id 
            where 1=1
            and c.estado_id = 1
            and c.catcosto_id = $categoria_id"
        )->result_array();
    }

    function delete_costo_producto($costo_producto){
        return $this->db->delete('costo_producto',array('cproducto_id'=>$costo_producto));
    }
    
    /*
     * retorna todos los costos de una categoria
     */
    function get_allcosto_categoria($catcosto_id){
        return $this->db->query(
            "SELECT c.*, cc.catcosto_descripcion, cc.catcosto_porcentaje,
                    e.estado_color, e.estado_descripcion
            from costo c 
            left join categoria_costo cc on c.catcosto_id = cc.catcosto_id 
            left join estado e on c.estado_id = e.estado_id 
            where
                c.catcosto_id = $catcosto_id"
        )->result_array();
    }
}
