<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Costo_descripcion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get costo_descripcion by costodesc_id
     */
    function get_costo_descripcion($costodesc_id)
    {
        $costo_descripcion = $this->db->query("
            SELECT
                *
            FROM
                `costo_descripcion`
            WHERE
                `costodesc_id` = ?
        ",array($costodesc_id))->row_array();

        return $costo_descripcion;
    }
    
    /*
     * Get all costo_descripcion count
     */
    function get_all_costo_descripcion_count()
    {
        $costo_descripcion = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `costo_descripcion`
        ")->row_array();

        return $costo_descripcion['count'];
    }
        
    /*
     * Get all costo_descripcion
     */
    function get_all_costo_descripcion()
    {
        $costo_descripcion = $this->db->query("
            SELECT
                *
            FROM
                `costo_descripcion`
            WHERE
                1 = 1
            ORDER BY `costodesc_descripcion`
        ")->result_array();

        return $costo_descripcion;
    }
        
    /*
     * function to add new costo_descripcion
     */
    function add_costo_descripcion($params)
    {
        $this->db->insert('costo_descripcion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update costo_descripcion
     */
    function update_costo_descripcion($costodesc_id,$params)
    {
        $this->db->where('costodesc_id',$costodesc_id);
        return $this->db->update('costo_descripcion',$params);
    }
    
    /*
     * function to delete costo_descripcion
     */
    function delete_costo_descripcion($costodesc_id)
    {
        return $this->db->delete('costo_descripcion',array('costodesc_id'=>$costodesc_id));
    }
}
