<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_produccion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * function to add new area
     */
    function add_detalle_produccion($params)
    {
        $this->db->insert('detalle_produccion',$params);
        return $this->db->insert_id();
    }
    
    function get_all_produccion($area_id){
        return $this->db->query(
            "SELECT ci.*, p.producto_nombre, dp.* 
            from control_inventario ci
            left join detalle_produccion dp on ci.controli_id = dp.controli_id 
            left join estado e on ci.estado_id = e.estado_id
            left join producto p on dp.producto_id = p.producto_id
            where 1=1
            and ci.area_id = $area_id"
        )->result_array();
    }

    function update_detalle($id, $params){
        $this->db->where('detproduccion_id',$id);
        return $this->db->update('detalle_produccion',$params);
    }
    /* obtiene todos los detalles de una producción */
    function get_all_detalleproduccion($produccion_id){
        return $this->db->query(
            "SELECT dp.*, p.producto_nombre, a.area_nombre, e.estado_color, e.estado_descripcion
            from detalle_produccion dp
            left join producto p on dp.producto_id = p.producto_id
            left join control_inventario ci on dp.controli_id = ci.controli_id 
            left join estado e on dp.estado_id = e.estado_id
            left join area a on ci.area_id = a.area_id
            where
                dp.produccion_id = $produccion_id
        ")->result_array();
    }

    function get_detproduccion($detproduccion_id){
        return $this->db->query(
            "SELECT dp.*
            from detalle_produccion dp
            where 1 = 1
            and dp.detproduccion_id = $detproduccion_id"
        )->result_array();
    }
}
