<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_produccion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_all_produccion($area_id){
        return $this->db->query(
            "SELECT ci.*, p.producto_nombre, dp.* 
            from control_inventario ci
            left join detalle_produccion dp on ci.controli_id = dp.controli_id 
            left join estado e on ci.estado_id = e.estado_id
            left join producto p on dp.producto_id = p.producto_id
            where 1=1
            and ci.area_id = $area_id"
        )->result_array();
    }

    function update_detalle($id, $params){
        $this->db->where('detproduccion_id',$id);
        return $this->db->update('detalle_produccion',$params);
    }
}
