<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perdida_factor_model extends CI_Model{
    function __construct()
    {
        parent::__construct();
    }
    /**
     * Return all costos for a producto
     */
    function get_all_perdida_factor(){
        return $this->db->query(
            "SELECT pf.*
            from perdida_factor pf
            order by pf.perdidaf_id asc"
        )->result_array();
    }

    function add_perdida_factor($params){
        $this->db->insert('perdida_factor',$params);
        return $this->db->insert_id();
    }

    function edit_perdida_factor($perdidaf_id,$params){
        $this->db->where('perdidaf_id',$perdidaf_id);
        return $this->db->update('perdida_factor',$params);
    }

    function get_perdida_factor($perdidaf_id){
        return $this->db->query(
            "select pf.*
            from perdida_factor pf
            where pf.perdidaf_id = $perdidaf_id"
        )->row_array();
    }
    
    /*
     * function to update perdida_factor
     */
    function update_perdida_factor($perdidaf_id,$params)
    {
        $this->db->where('perdidaf_id',$perdidaf_id);
        return $this->db->update('perdida_factor',$params);
    }
}
