<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perdida_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * function to add new perdida
     */
    function add_perdida($params)
    {
        $this->db->insert('perdida',$params);
        return $this->db->insert_id();
    }
    
    function update_perdida($perdida_id, $params){
        $this->db->where('perdida_id',$perdida_id);
        return $this->db->update('perdida',$params);
    }
    
    /*
     * function to delete perdida
     */
    function delete_perdida($perdida_id)
    {
        return $this->db->delete('perdida',array('perdida_id'=>$perdida_id));
    }
    
    /* get peridas de un detalle de producción */
    function get_perdidas_platabanda($detproduccion_id){
        return $this->db->query(
            "SELECT p.*, e.estado_color, e.estado_descripcion
            from perdida p
            left join estado e on p.estado_id = e.estado_id
            where
                p.detproduccion_id = $detproduccion_id "
        )->result_array();
    }
    
}
