<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perdida_detalle_model extends CI_Model{
    function __construct()
    {
        parent::__construct();
    }
    /**
     * Return all costos for a producto
     */
    function get_all_perdida_detalle(){
        return $this->db->query(
            "SELECT pd.*, pf.perdidaf_descripcion
            from perdida_detalle pd
            left join perdida_factor pf on pd.perdidaf_id = pf.perdidaf_id
            group by pd.perdidaf_id, pd.perdidad_id
            order by pf.perdidaf_id  asc, pd.perdidad_descripcion asc"
        )->result_array();
    }

    function add_perdida_detalle($params){
        $this->db->insert('perdida_detalle',$params);
        return $this->db->insert_id();
    }

    function edit_perdida_detalle($perdidad_id,$params){
        $this->db->where('perdidad_id',$perdidad_id);
        return $this->db->update('perdida_detalle',$params);
    }

    function get_perdida_detalle($perdidad_id){
        return $this->db->query(
            "select pd.*, pf.perdidaf_descripcion
            from perdida_detalle pd
            left join perdida_factor pf on pd.perdidaf_id = pf.perdidaf_id
            where pd.perdidad_id = $perdidad_id"
        )->row_array();
    }
    
    /*
     * function to update perdida_detalle
     */
    function update_perdida_detalle($perdidad_id,$params)
    {
        $this->db->where('perdidad_id',$perdidad_id);
        return $this->db->update('perdida_detalle',$params);
    }
}
